import "./founder.css";
import founder from "../../assets/founder.png";

function Founder() {
    return (
        <div>
            <div className="mx-auto grid md:grid-cols-3 grid-cols-1 gap-0 md:gap-10 mt-14 m-0 md:mb-14 ">
                <div className="col-span-1 ">
                    <img className=" h-60 mb-10 md:mb-0 mx-auto sm:h-96 md:h-auto" src={founder} alt="a"/>
                </div>
                <div className="col-span-2 max-w-md ">
                    <p className="text-[16px] text-[#7e7e7e] font-[400] mb-5">Mr. Thomas Christopher is the CEO and Founder of BITCOVERSE, A Community For Everyone. Tom, is a former Actor / Model and Athlete, from New York City, who turned private Businessman at 24 years old. Key investment industries include: precious metals and gemstones (active mining partner), sports wagering, real estate (virtual as well), and blockchain technology, which is currently a key focus of Tom's investment plans. He is known to be a forward thinker who believes in innovation and usually sees things 3-10 years into the future.One of his latest ventures is with the brand, Toppem Sports, a subsidiary of its' parent company, Toppem. Toppem Sports integrates the worlds of Fantasy Sports and blockchain technology via NFTs, tokenization, and gamification. Feel free to review the company.</p>
                    <a className="checkout-link mb-5 text-sm cursor-pointer"><span className="font-bold text-lg">Please Check Out:</span> www.toppemsports.io</a>
                    <p className="text-[16px] text-[#7e7e7e] font-[400]  mb-5">One of the most influential people in Tom's life is his mother, Jeanette. Tom grew up with three other siblings and life was challenging growing up in a one bedroom apartment in NYC. His father was not a responsible parent and the burden of providing for the family fell on Jeanette. The sad part was his father could not get past his issues of irresponsibility (alcohol and gambling) and took it out on his family. Tom witnessed his mother being belittled due to her gender and he vowed not to live life with that perspective. He did not feel it was right. This is one important motivational factor in his life, the right for equality and inclusion for all women regardless of their interests both personally and professionally</p>
                    <p className="text-[16px] text-[#7e7e7e] font-[400]  mb-5">Tom’s love and infatuation for blockchain and cryptocurrency began once he took the time out to truly understand them and how they were going to affect the future of global money. The key to truly understanding both blockchain and crypto's is networking with the people in the community and learning from each other. </p>
                </div>
            </div>
            <div className="mx-auto max-w-3xl">
                    <p className="text-[16px] text-[#7e7e7e] font-[400] semibold mb-5">This is part of the equation that Tom uses to determine his next trade. The other two parts to Tom’s success is performing independent research and trusting his own intuition. Tom’s niche are long term crypto trades (much like a CD baring interest, but with Digital Assets/currencies instead, known as "Alt Coins") and blockchain offerings. He focuses on Alt Coins that serve as a necessity with a purpose now and moving forward into the next 10 – 20 years in shaping and transforming society on a global scale transitioning into a new financial system. This method produces fast gains now but also preserves wealth for the future. </p>
                    <p className="text-[16px] text-[#7e7e7e] font-[400]  mb-5">Tom is a big advocate of true education that enhances societal knowledge that is both self and communal sustainable. One of the biggest emphasis that BITOVERSE concentrates on is education. Its' educational platform is second to none. With over 126 developed courses for certificates and diplomas (degrees are under development) Tom is very proud to roll out the "Learn To Earn" program. Be sure to review the learn to earn program for all seven (more in development) subjects made available. Tom believes in equality and inclusion that is sustainable for a brighter future. He truly wants BITCOVERSE to be A Community For Everyone.</p>
                    <p className="text-[16px] text-[#7e7e7e] font-[400]  mb-5">One of Tom's influencer's is FUBU Co-Founder and Entrepreneur, Daymond John. Tom aspires to be like Mr. John. Toppem Sports hopes to be able to next cross over into the urban apparel fashion industry with that modern, confident, and edgy look. The same belief and attitude that FUBU walked onto the streets with and why its popularity has never faded amongst its loyal and new supporters decades later. Mr. John had a clear vision and executed it flawlessly and is now reaping the benefits 30 years later due to this. This is one of what Tom's goals are for BITCOVERSE, A Community For Everyone, down the road. Legacy is the goal of attainment for BITCOVERSE.</p>
                    <p className="text-[16px] text-[#7e7e7e] font-[400]  mb-5">Tom is a College graduate with a Bachelor of Arts degree in Sociology. His passions include being a better Dad each day that passes he can be with his six year old son, both engaging and watching sports, eating, and traveling to different parts of the world while meeting and learning about as many new people as possible! He is a firm believer of Spiritual growth as a person. All of his life experiences have </p>
                    <p className="text-[16px] text-[#7e7e7e] font-[400]  mb-5">Tom is a College graduate with a Bachelor of Arts degree in Sociology. His passions include being a better Dad each day that passes he can be with his six year old son, both engaging and watching sports, eating, and traveling to different parts of the world while meeting and learning about as many new people as possible! He is a firm believer of Spiritual growth as a person. All of his life experiences have culminated into his existence as a Leader at this present moment. He looks forward to assisting as many people as possible in order to achieve goals of communal and self sustainability in all aspects of life.  </p>
            </div>
        </div>
    )
}

export default Founder;